version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v1.7.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/link-checker .

  publishImage:
    docker:
      - image: web3f/ci-commons:v1.7.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/link-checker

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - buildImage:
          filters:
            tags:
              only: /.*/
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - buildImage
